'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Report

    '''<summary>
    '''carTabPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents carTabPage As Global.DevExpress.Web.ASPxPageControl

    '''<summary>
    '''ContentControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl1 As Global.DevExpress.Web.ContentControl

    '''<summary>
    '''ASPxDocumentViewer2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxDocumentViewer2 As Global.DevExpress.XtraReports.Web.ASPxDocumentViewer

    '''<summary>
    '''ContentControl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl2 As Global.DevExpress.Web.ContentControl

    '''<summary>
    '''ASPxDocumentViewer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxDocumentViewer1 As Global.DevExpress.XtraReports.Web.ASPxDocumentViewer

    '''<summary>
    '''ContentControl3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl3 As Global.DevExpress.Web.ContentControl

    '''<summary>
    '''ASPxDocumentViewer3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxDocumentViewer3 As Global.DevExpress.XtraReports.Web.ASPxDocumentViewer

    '''<summary>
    '''ContentControl4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl4 As Global.DevExpress.Web.ContentControl

    '''<summary>
    '''ASPxDocumentViewer4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxDocumentViewer4 As Global.DevExpress.XtraReports.Web.ASPxDocumentViewer
End Class
