'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''ASPxImageSlider1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxImageSlider1 As Global.DevExpress.Web.ASPxImageSlider

    '''<summary>
    '''gv_Herb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_Herb As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''gv_DiseaseShow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_DiseaseShow As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''Disease_SH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Disease_SH As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''gv_ArticleShow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_ArticleShow As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''Article_SH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Article_SH As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''gv_InfoShow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_InfoShow As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''Info_SH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Info_SH As Global.System.Web.UI.WebControls.SqlDataSource
End Class
